### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by pakarat044**
- Add tests for login, registration, and reservation
- Add end-to-end tests with behave

### CODE REVIEW

**Review by jeanyjean — APPROVED** [review]
Good testing that should cover most of the codes.
Good end-to-end testing that is also easy to read and understand.

**Review by PitchapaSaelim — APPROVED** [review]
Good tests improve code quality, well done!

**Review by PanidaOun — APPROVED** [review]
Very good end-to-end test!

**Review by nuttapol-kor — APPROVED** [review]
The tests pass and nice E2E testing with behave.

**Review by vnsvakanda — APPROVED** [review]
Excellent job on end-to-end test. Well done!

**Pull request merged**
